function out1 = uavPathFollowStateFcn(in1,phi)
%UAVPATHFOLLOWSTATEFCN
%    OUT1 = UAVPATHFOLLOWSTATEFCN(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Apr-2020 18:40:33
g = 9.8;
V = 18;
psi = in1(1,:);
if psi > pi
    psi = psi-2*pi;
elseif psi < -pi
    psi = psi+2*pi;
end
out1 = [tan(phi).*g./V;sin(psi).*V];