function [A,B] = uavPathFollowStateJacobianFcn(in1,u1)
%UAVPATHFOLLOWSTATEJACOBIANFCN
%    [A,B] = UAVPATHFOLLOWSTATEJACOBIANFCN(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Apr-2020 18:40:33

psi = in1(1,:);
A = reshape([0.0,cos(psi).*1.8e+1,0.0,0.0],[2,2]);
if nargout > 1
    B = [tan(u1).^2.*(1.09e+2./2.0e+2)+1.09e+2./2.0e+2;0.0];
end
