function TestCase_Task = TaskTestCase_StartTaskNormal()
% Task模块测试用例 1
TestCase_Task.GroundStation.MavlinkCmd76.time = [0 15 50 80];
TestCase_Task.GroundStation.MavlinkCmd76.data = [...
    ENUM_Mav76.Mav76_None,...
    ENUM_Mav76.Mav76_SwitchHeight,...
    ENUM_Mav76.Mav76_TakeOff,...
    ENUM_Mav76.Mav76_Continue];