% SENSOR_ALIGNMENT_PARAM_V1000.IMU1.Rbs = eye(3); % Vb = Rbs * Vs
% SENSOR_ALIGNMENT_PARAM_V1000.IMU2.Rbs = SENSOR_ALIGNMENT_PARAM_V1000.IMU1.Rbs;
% SENSOR_ALIGNMENT_PARAM_V1000.IMU3.Rbs = SENSOR_ALIGNMENT_PARAM_V1000.IMU1.Rbs;
busSensorAlignment = 'BUS_SENSOR_ALIGNMENT_PARAM';
%% V1000
SENSOR_ALIGNMENT_PARAM_V1000 = Simulink.Bus.createMATLABStruct(busSensorAlignment);
SENSOR_ALIGNMENT_PARAM_V1000.Mag1.Rbs = ...
    [ 0 -1  0;
    -1  0  0;
    0  0 -1;];
SENSOR_ALIGNMENT_PARAM_V1000.Mag2.Rbs = SENSOR_ALIGNMENT_PARAM_V1000.Mag1.Rbs;
%% V10 V10s
SENSOR_ALIGNMENT_PARAM_V10 = Simulink.Bus.createMATLABStruct(busSensorAlignment);
SENSOR_ALIGNMENT_PARAM_V10 = SENSOR_ALIGNMENT_PARAM_V1000;
%% V10_1
SENSOR_ALIGNMENT_PARAM_V10_1 = Simulink.Bus.createMATLABStruct(busSensorAlignment);
SENSOR_ALIGNMENT_PARAM_V10_1.Mag1.Rbs = eye(3);
SENSOR_ALIGNMENT_PARAM_V10_1.Mag2.Rbs = SENSOR_ALIGNMENT_PARAM_V10_1.Mag1.Rbs;

